apiVersion: v1
kind: Service
metadata:
  name: gcr-hello-"{{ .Values.env }}"
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  selector:
    app: gcr-hello-"{{ .Values.env }}"
